# color scheme
import = ["~/.config/alacritty/colorschemes/catppuccin/catppuccin-macchiato.toml"]


# font settings
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"                 #I don't really like italics in the terminal

[font]
size = 13.5

# mouse settings
[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"
