# color scheme
import = ["~/.config/alacritty/colorschemes/sonokai/andromeda.toml"]

# font settings
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Regular"                 #I don't really like italics in my terminal

[font]
size = 15.0

# mouse settings
[selection]
save_to_clipboard = true
